# Config file for automatic testing at travis-ci.org
dist: bionic
language: python
arch:  
    - arm64
python:
    - "3.8"

before_install:
    - PROTOBUF_VERSION=3.17.3
    - PROTOC_FILENAME=protoc-3.17.3-linux-aarch_64.zip
    - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-aarch_64.zip
    - unzip $PROTOC_FILENAME -d $HOME/.local
    # We have to install protoc, and python libs for both python and python3, since mypy runs py3
    - sudo apt-get install -qq python3-pip python3-setuptools
    - unset PYENV_ROOT
    - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
    - export PATH="$HOME/.pyenv/bin:$PATH"
    - pyenv install 3.8.11
    - python3 -m pip install virtualenv
script:
    - ./run_test.sh


jobs:
    include:
        - python: 3.8
