name: CI

# Run on git push, PR, or manually from the Actions tab
on: [push, pull_request, workflow_dispatch]

jobs:

  
  armv64_job:
      name: Build and Test for arm64
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3 python3-pip curl git make build-essential libssl-dev zlib1g-dev wget && \
              git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
              echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc && \
              echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc && \
              echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init -)"\nfi' >> ~/.bashrc && \
              exec "$SHELL" && \
              
              deactivate'
